query DeckShow($id: ID!) {
  deck(id: $id) {
    id
    name
    ...DeckOnDeckQuizEmpty
  }

  cards(input: { where: { deckId: $id } }) {
    cards {
      id
      ...CardOnDeckQuiz
    }
    pageInfo {
      totalCount
    }
  }
}
