import Head from 'next/head'
import { Home } from '@/components/template/home'

export default function IndexPage() {
  return (
    <>
      <Head>
        <title>反復学習に特化した英語学習アプリ | Phraze</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
    </>
  )
}
